# Dependencies
markdown:         kramdown
kramdown:
  extensions: ["tables"]
  math_engine: mathjax
     
highlighter:         rouge
 
# Permalinks
permalink:        pretty

# Setup
title:            Mandar Deshpande
tagline:          'Machine Learning Researcher'
url:              http://www.mandroid6.github.io
shorturl:         mandroid6.github.io

author:
  name:           'Mandar Deshpande'  
  url:            https://www.linkedin.com/in/mandardeshpande1995/


paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/mandroid6/mandroid6.github.io  
 
     
footer-links:
  dribbble:
  email: mandar6@ucla.edu
  facebook: Mandar.Deshpande.6
  flickr:
  github: mandroid6
  instagram: mandroid6
  linkedin: mandardeshpande1995/
  pinterest:
  twitter: mandroid_6
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: MandarDeshpande6
# This is the list of pages to include in the header of the website.
pages_list:       
  Archive: '/archive/'
  GitHub: 'https://github.com/mandroid6'
  MOOCS: '/moocs'
  Resume: '/assets/resume.pdf'
  About: '/about/'
  
# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
  - jekyll-paginate
