# Dependencies
markdown:         kramdown
kramdown:
  extensions: ["tables"]
  math_engine: mathjax

highlighter:         rouge

# Permalinks
permalink:        pretty

# Setup
title:            Mandar Deshpande
tagline:          'Model Optimization Engineer'
url:              http://www.mandroid6.github.io
shorturl:         mandroid6.github.io

author:
  name:           'Mandar Deshpande'
  url:            https://www.linkedin.com/in/mandroid6/


paginate:         1

# Custom vars
version:          2.0.0

github:
  repo:           github.com/mandroid6/mandroid6.github.io


footer-links:
  dribbble:
  email: razzormandar@gmail.com
  facebook: Mandar.Deshpande.6
  flickr:
  github: mandroid6
  instagram: mandroid6
  linkedin: mandroid6/
  pinterest:
  twitter: mandroid_6
  stackoverflow:
  youtube: MandarDeshpande6

# Navigation
pages_list:
  About: '/about/'
  Archive: '/archive/'
  Courses: '/moocs/'
  Medium: 'https://medium.com/@razzormandar'
  GitHub: 'https://github.com/mandroid6'

# Allow URL Redirects:
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
  - jekyll-paginate
